apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-worker
  labels:
    role: worker
spec:
  replicas: 2
  selector:
    matchLabels:
      role: worker
  template:
    metadata:
      labels:
        role: worker
    spec:
      containers:
      - name: locust-worker
        image: locustio/locust
        args: 
        - --master-host 
        - locust-master.default.svc.cluster.local
        - --host
        - https://digitalocean.com
        - "--worker"
        resources:
          limits:
            cpu: 100m
            memory: 512Mi
          requests:
            cpu: 50m
            memory: 256Mi
        volumeMounts:
        - name: locust
          mountPath: /home/locust
      volumes:
      - name: locust
        configMap:
          name: locust-file
