apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-master
  labels:
    role: master
spec:
  replicas: 1
  selector:
    matchLabels:
      role: master
  template:
    metadata:
      labels:
        role: master
    spec:
      containers:
      - name: locust-master
        image: k8s.gcr.io/busybox
        command: ["/bin/sh","-c","cat /mnt/locust/app.py"]
        volumeMounts:
        - name: locust
          mountPath: /mnt/locust
      volumes:
      - name: locust
        configMap:
          name: locust-file
