apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: locust-worker
  labels:
    role: worker
spec:
  selector:
    matchLabels:
      role: worker
  template:
    metadata:
      labels:
        role: worker
    spec:
      containers:
      - name: locust-worker
        image: locustio/locust
        env:
        - name: LOCUST_HOST
          value: https://digitalocean.com
        - name: LOCUST_MASTER_NODE_HOST
          value: 10.245.135.31
        - name: LOCUST_MASTER_NODE_PORT
          value: "5557"
        - name: LOCUST_LOGLEVEL
          value: INFO
        - name: LOCUST_LOCUSTFILE
          value: "/mnt/locust/app.py"
        args: 
        - "--worker"
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 500m
            memory: 256Mi
        volumeMounts:
        - name: locust
          mountPath: /mnt/locust
      volumes:
      - name: locust
        configMap:
          name: locust-file
