apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: locust-worker
  labels:
    role: worker
spec:
#  replicas: 4
  selector:
    matchLabels:
      role: worker
  template:
    metadata:
      labels:
        role: worker
    spec:
      containers:
      - name: locust-worker
        image: locustio/locust
        args: 
        - "-f"
        - "/mnt/locust/app.py"
        - "--worker"
        - "--master-port"
        - "5557"
        - "--master-host"
        - "locust-master-svc.default.svc.cluster.local"
        - "QuickStartUser"
        volumeMounts:
        - name: locust
          mountPath: /mnt/locust
      volumes:
      - name: locust
        configMap:
          name: locust-file
