apiVersion: v1
kind: Service
metadata:
  name: locust-master-svc
  labels:
    role: master
spec:
  ports:
  - port: 5557
    targetPort: 5557
    protocol: TCP
    name: locust
  selector:
    role: master
