apiVersion: v1
kind: Service
metadata:
  name: locust-master
  labels:
    role: master
spec:
  type: ClusterIP
  ports:
  - port: 5557
    targetPort: 5557
    protocol: TCP
    name: headless-p1
  - port: 5558
    targetPort: 5558
    name: headless-p2
  - port: 8089
    targetPort: 8089
    name: web
  selector:
    role: master
